### ISSUE TITLE
Node-CoT MissionChange Error

### ISSUE THREAD

**Issue by ingalls** [dfpc-coe/CloudTAK#277]
```
{"MissionChange":{"contentUid":{"_text":"layer-11-27529-1"},"creatorUid":{"_text":"CN=mma-etl-user@cotak.gov,OU=WILDFIRE,O=CO-TAK"},"isFederatedChange":{"_text":"false"},"
missionName":{"_text":"Colorado NIFS Fire Perimeters"},"timestamp":{"_text":"2024-08-16T15:21:55.361Z"},"type":{"_text":"ADD_CONTENT"},"details":{"_attributes":{"type":"t-x-d-d"}}}}                             
Error TypeError: Cannot read properties of undefined (reading '_attributes')                                                                                                   at CoT.to_geojson (file:///home/state/Development/dfpc/node-cot/lib/cot.ts:679:70)
    at ConnectionPool.cots (file:///home/state/Development/dfpc/CloudTAK/api/lib/connection-pool.ts:1:2030)                                                                    at TAK.<anonymous> (file:///home/state/Development/dfpc/CloudTAK/api/lib/connection-pool.ts:1:3937)
    at TAK.emit (node:events:520:28)                                                                                                                                           at TLSSocket.<anonymous> (file:///home/state/Development/dfpc/CloudTAK/api/node_modules/@tak-ps/node-tak/index.ts:1:2127)
    at TLSSocket.emit (node:events:520:28)                                                                                                                                     at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)

```

**Comment by ingalls** [comment]
Closed by: https://github.com/dfpc-coe/CloudTAK/pull/274
