### ISSUE TITLE
Current Location Error

### ISSUE THREAD

**Issue by ingalls** [dfpc-coe/CloudTAK#402]
```
TypeError: Cannot read properties of undefined (reading 'coordinates')
    at Proxy.getLocation (https://map.cotak.gov/assets/Home.js:59:26546)
    at Ur (https://map.cotak.gov/assets/index.js:14:38)
    at tn (https://map.cotak.gov/assets/index.js:14:109)
    at SVGSVGElement.s (https://map.cotak.gov/assets/index.js:18:4003)
```

**Comment by ingalls** [comment]
Fixed.
